### ISSUE TITLE
关于 macOS 版本的问题

### ISSUE THREAD

**Issue by linehk** [TioaTyan/Hackintosh_Hasee_Z6-SL7D1#1]
我使用这个配置文件在 macOS 10.14 出现了无法找到声音输出的问题；
在 macOS 10.13.6 出现了亮度不能保存、触摸板无法关闭等小问题。
希望您能告诉我哪个版本的 macOS 适合这个配置或者能更新到 10.14 都能完美驱动就更好了。

**Comment by TioaChan** [comment]
10.13.6正常使用，笔记本已闲置，10.14未测试
